/**
 * chat-001 —— 抽屉里的**长段静态文案**（首次须知 + 完整条款）。
 *
 * 为什么不放在 `src/locales/*.json`：那两个文件被 `src/i18n.ts` **静态 import**，
 * 会整包进主包 —— 而这两段是"只有打开对话抽屉才可能读到"的内容。
 * 放这里等于让不会碰对话的访客也付这份体积（两语言合计约 5.2 kB，占 `sections.chat` 的六成）。
 *
 * 代价与补偿：
 *   - 代价：`lint:locales` 的 zh/en 键对齐**不再覆盖**这两段。
 *   - 补偿：同一个文件里两种语言紧邻书写 + 模块级数量断言（下方），改一处能立刻看到另一处。
 *   - 纯标签文案（按钮、输入框、降级提示等）仍留在 locales，仍受 `lint:locales` 保护。
 */

export type ChatCopyLang = "zh" | "en";

/** L2 首次须知（5 条，非阻塞，`sessionStorage` 记住）。 */
export const CHAT_NOTICE: Record<ChatCopyLang, readonly string[]> = {
  zh: [
    "这是个人性质的粉丝向技术演示，与所引用作品的版权方没有任何隶属、合作或授权关系。",
    "台词由 AI 依据角色设定实时生成，不是原作台词，也可能偏离设定。",
    "请不要输入真实姓名、住址、联系方式等个人信息。",
    "仅供个人娱乐，请勿用于商业用途或二次传播。",
    "角色以中文为主，因此在任何界面语言下回复都是中文。",
  ],
  en: [
    "This is a personal fan-made technical demo. It is not affiliated with, endorsed by or licensed by the rights holders of the works referenced.",
    "Replies are generated by AI from character settings. They are not lines from the original works and may drift off-character.",
    "Please do not type real names, addresses or contact details.",
    "For personal entertainment only. Do not use it commercially or repost the outputs.",
    "Characters speak mainly Chinese, so replies stay in Chinese whatever the interface language is.",
  ],
};

/** L3 完整条款（11 条）。 */
export const CHAT_TERMS: Record<ChatCopyLang, readonly string[]> = {
  zh: [
    "本站是个人性质的、非商业的粉丝向技术演示，与所引用作品的作者、版权方、发行方、运营方不存在任何隶属、合作、赞助或授权关系。",
    "角色名称、形象、设定及相关素材的一切权利归各自权利人所有。本站仅在展示与学习研究的范围内引用，不主张任何相关权利，也不因本功能收取任何费用。",
    "对话内容由大语言模型依据角色设定实时生成，不是原作台词，也不是官方设定，可能存在事实错误、设定偏差或与剧情冲突之处，不代表本站或任何权利人的立场。",
    "本功能面向成年受众，部分角色设定包含成人向剧情背景。未成年人请在监护人指导下使用。",
    "不得利用本功能生成或传播违反法律法规、公序良俗的内容；不得诱导生成涉政、涉黄、暴力、仇恨、自伤等内容；不得绕过安全策略或限流；不得批量抓取、转售或代理转发模型能力；不得将生成内容用于训练其他模型或任何商业用途。",
    "本功能不收费、不投放广告、不用于商业推广。请勿将生成内容用于任何商业目的。",
    "本站不保存对话内容，服务端只保留不含内容的计数日志。请不要在对话中输入真实姓名、住址、身份证号、联系方式、账号密码等个人信息。请求会经本站服务端转发至第三方大模型服务，其数据处理规则以该服务的官方条款为准。",
    "本功能为免费技术演示，不承诺稳定性、准确性、连续性或长期可用；可能因额度、维护、升级或权利人要求等原因随时限流、降级或下线，恕不另行通知。",
    "在适用法律允许的范围内，因使用本功能或依赖其生成内容所产生的任何后果由使用者自行承担；本站不对生成内容的准确性、适用性、合法性作任何明示或默示担保。",
    "如权利人认为本站内容侵犯其合法权益，可通过页脚通讯区的联系方式提出，本站将在核验后及时处理，包括删除相关内容或下线本功能。",
    "首次使用本功能即视为已阅读并同意以上条款；条款变更后继续使用即视为接受变更后的版本。",
  ],
  en: [
    "This is a personal, non-commercial fan-made technical demo. It is not affiliated with, endorsed by, sponsored by or licensed by the authors, rights holders, publishers or operators of the works referenced.",
    "All rights to character names, likenesses, settings and related assets belong to their respective owners. We claim no rights and charge no fee for this feature.",
    "Replies are generated by a large language model from character settings in real time. They are not lines from the original works and may be inaccurate or off-character. They do not represent the views of this site or of any rights holder.",
    "Intended for adults. Some characters carry mature storylines. Minors should use it under guardian supervision.",
    "You must not use this feature to generate or spread unlawful or harmful content, to induce political, sexual, violent, hateful or self-harm content, to bypass safety or rate limits, to scrape or resell the model capability, or to use outputs for training other models or for any commercial purpose.",
    "No fee, no ads, no commercial promotion. Do not use outputs commercially.",
    "Conversations are not stored; the server keeps only content-free counters. Do not enter personal information such as real names, addresses, ID numbers, contact details or passwords. Requests are relayed through our server to a third-party model service, whose own terms apply.",
    "A free demo: no guarantee of stability, accuracy, continuity or long-term availability. The feature may be rate-limited, degraded or removed at any time without notice.",
    "To the extent permitted by law, you use this feature and its outputs at your own risk; no warranty of accuracy, fitness or legality is given.",
    "Rights holders may contact us via the footer channels; we will review and act promptly, including removing content or taking the feature offline.",
    "First use constitutes acceptance of these terms; continued use after changes constitutes acceptance of the revised terms.",
  ],
};

/**
 * 抽屉内的**短标签**（24 个）。只有打开抽屉的人会读到，所以和须知/条款一样
 * 放在这里、随懒 chunk 加载，不进主包 —— 这是 chat-001 那条「主包不得上涨超过 3 kB」
 * 的主要来源。locales 里只留主包那个「聊聊」按钮要读的 `launch` / `launchAria`。
 *
 * `en` 声明为 `typeof ZH_CHAT_LABELS`：少一个键、多一个键、函数签名不一致都是
 * **编译错误**。`lint:locales` 的存在性检查不再覆盖这批键，由这条类型约束接替。
 */
const ZH_CHAT_LABELS = {
  clear: "清空重来",
  close: "关闭对话",
  degradedDisabled: "生成服务已暂停 · 本次为预设台词",
  degradedError: "生成服务暂不可用 · 本次为预设台词",
  degradedQuota: "演示余量已满 · 本次为预设台词",
  degradedUnavailable: "本站当前未接入生成服务 · 本次为预设台词",
  footerNote: "AI 生成 · 内容仅作演示，非官方",
  inputLabel: "输入消息",
  inputPlaceholder: "说点什么…",
  languageTag: "中文优先",
  limitReached: (name: string) => "这次聊到上限了。想继续，可以把 " + name + " 的 SoulPod 下载到本地，或放到设备上继续。",
  nextStepDevice: "看看能部署它的设备",
  nextStepTitle: "然后呢",
  noticeAccept: "我知道了",
  noticeTitle: "开始之前",
  openersTitle: "可以这样开始",
  retry: "重试",
  send: "发送",
  termsBack: "返回对话",
  termsLink: "完整声明",
  termsTitle: "完整声明",
  turnBudget: (n: number) => "本次对话还剩 " + n + " 轮",
  typing: "正在输入",
  unofficial: "粉丝演示 · 非官方",
};

const EN_CHAT_LABELS: typeof ZH_CHAT_LABELS = {
  clear: "Start over",
  close: "Close chat",
  degradedDisabled: "Generation is paused · scripted reply",
  degradedError: "Generation temporarily unavailable · scripted reply",
  degradedQuota: "Demo quota used up · scripted reply",
  degradedUnavailable: "This site is not connected to a live model · scripted reply",
  footerNote: "AI-generated · demo only, unofficial",
  inputLabel: "Message",
  inputPlaceholder: "Say something…",
  languageTag: "ZH-led",
  limitReached: (name: string) => "That is the end of this session. To keep going, download " + name + "'s SoulPod or run it on the device.",
  nextStepDevice: "See the device it runs on",
  nextStepTitle: "Next",
  noticeAccept: "Got it",
  noticeTitle: "Before you start",
  openersTitle: "You could start with",
  retry: "Retry",
  send: "Send",
  termsBack: "Back to chat",
  termsLink: "Full statement",
  termsTitle: "Full statement",
  turnBudget: (n: number) => "" + n + " turns left in this session",
  typing: "Typing",
  unofficial: "Fan demo · Unofficial",
};

export type ChatLabels = typeof ZH_CHAT_LABELS;

export const CHAT_LABELS: Record<ChatCopyLang, ChatLabels> = {
  zh: ZH_CHAT_LABELS,
  en: EN_CHAT_LABELS,
};

/** 归一化语言标记 → `zh` / `en`。站点只有这两种语言，未知一律回落到 `zh`。 */
export function toChatCopyLang(lng: string | undefined): ChatCopyLang {
  return (lng ?? "zh").toLowerCase().startsWith("en") ? "en" : "zh";
}

// 开发期一致性断言：中英条数必须一致，否则某一边会"少一条"而没人发现。
// （`CHAT_LABELS` 的键集不在这里查 —— 它由 `typeof ZH_CHAT_LABELS` 在编译期保证。）
if (import.meta.env.DEV) {
  for (const [name, group] of [
    ["CHAT_NOTICE", CHAT_NOTICE],
    ["CHAT_TERMS", CHAT_TERMS],
  ] as const) {
    if (group.zh.length !== group.en.length) {
      console.warn(`[chat] ${name} 中英条数不一致: zh=${group.zh.length} en=${group.en.length}`);
    }
  }
}
